export const SET_USER = 'SET_USER';
// export const SET_ADS = 'SET_ADS';

export const FETCH_ADS_REQUEST = 'FETCH_ADS_REQUEST'
export const FETCH_ADS_FAILURE = 'FETCH_ADS_FAILURE';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';

export const FETCH_SINGLE_AD_REQUEST = 'FETCH_SINGLE_AD_REQUEST'
export const FETCH_SINGLE_AD_SUCCESS = 'FETCH_SINGLE_AD_SUCCESS'
export const FETCH_SINGLE_AD_FAILURE = 'FETCH_SINGLE_AD_FAILURE'

export const FETCH_SEARCH_ADS_REQUEST = 'FETCH_SEARCH_ADS_REQUEST'
export const FETCH_SEARCH_ADS_SUCCESS = 'FETCH_SEARCH_ADS_SUCCESS'
export const FETCH_SEARCH_ADS_FAILURE = 'FETCH_SEARCH_ADS_FAILURE'


export const EDIT_AD_REQUEST = 'EDIT_AD_REQUEST'
export const EDIT_AD_SUCCESS = 'EDIT_AD_SUCCESS'
export const EDIT_AD_FAILURE = 'EDIT_AD_FAILURE'
